print("First editing")
print("Second editing")
print("Third editing")
print("Now we check git add")
print("if !add & commited & remove, but it have in another branch - it can repair")
print("Main must commit")
